// Generated by gencpp from file rocon_interaction_msgs/GetRoles.msg
// DO NOT EDIT!


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_GETROLES_H
#define ROCON_INTERACTION_MSGS_MESSAGE_GETROLES_H

#include <ros/service_traits.h>


#include <rocon_interaction_msgs/GetRolesRequest.h>
#include <rocon_interaction_msgs/GetRolesResponse.h>


namespace rocon_interaction_msgs
{

struct GetRoles
{

typedef GetRolesRequest Request;
typedef GetRolesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRoles
} // namespace rocon_interaction_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rocon_interaction_msgs::GetRoles > {
  static const char* value()
  {
    return "bb1af0e7038bd0c25a66561b0d17c47c";
  }

  static const char* value(const ::rocon_interaction_msgs::GetRoles&) { return value(); }
};

template<>
struct DataType< ::rocon_interaction_msgs::GetRoles > {
  static const char* value()
  {
    return "rocon_interaction_msgs/GetRoles";
  }

  static const char* value(const ::rocon_interaction_msgs::GetRoles&) { return value(); }
};


// service_traits::MD5Sum< ::rocon_interaction_msgs::GetRolesRequest> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::GetRoles > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::GetRolesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::GetRoles >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetRolesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::GetRolesRequest> should match 
// service_traits::DataType< ::rocon_interaction_msgs::GetRoles > 
template<>
struct DataType< ::rocon_interaction_msgs::GetRolesRequest>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::GetRoles >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetRolesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rocon_interaction_msgs::GetRolesResponse> should match 
// service_traits::MD5Sum< ::rocon_interaction_msgs::GetRoles > 
template<>
struct MD5Sum< ::rocon_interaction_msgs::GetRolesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rocon_interaction_msgs::GetRoles >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetRolesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rocon_interaction_msgs::GetRolesResponse> should match 
// service_traits::DataType< ::rocon_interaction_msgs::GetRoles > 
template<>
struct DataType< ::rocon_interaction_msgs::GetRolesResponse>
{
  static const char* value()
  {
    return DataType< ::rocon_interaction_msgs::GetRoles >::value();
  }
  static const char* value(const ::rocon_interaction_msgs::GetRolesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_GETROLES_H
