// Generated by gencpp from file rocon_interaction_msgs/InteractiveClients.msg
// DO NOT EDIT!


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_INTERACTIVECLIENTS_H
#define ROCON_INTERACTION_MSGS_MESSAGE_INTERACTIVECLIENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rocon_interaction_msgs/InteractiveClient.h>
#include <rocon_interaction_msgs/InteractiveClient.h>

namespace rocon_interaction_msgs
{
template <class ContainerAllocator>
struct InteractiveClients_
{
  typedef InteractiveClients_<ContainerAllocator> Type;

  InteractiveClients_()
    : idle_clients()
    , running_clients()  {
    }
  InteractiveClients_(const ContainerAllocator& _alloc)
    : idle_clients(_alloc)
    , running_clients(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::rocon_interaction_msgs::InteractiveClient_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rocon_interaction_msgs::InteractiveClient_<ContainerAllocator> >::other >  _idle_clients_type;
  _idle_clients_type idle_clients;

   typedef std::vector< ::rocon_interaction_msgs::InteractiveClient_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::rocon_interaction_msgs::InteractiveClient_<ContainerAllocator> >::other >  _running_clients_type;
  _running_clients_type running_clients;




  typedef boost::shared_ptr< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> const> ConstPtr;

}; // struct InteractiveClients_

typedef ::rocon_interaction_msgs::InteractiveClients_<std::allocator<void> > InteractiveClients;

typedef boost::shared_ptr< ::rocon_interaction_msgs::InteractiveClients > InteractiveClientsPtr;
typedef boost::shared_ptr< ::rocon_interaction_msgs::InteractiveClients const> InteractiveClientsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rocon_interaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rocon_std_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_std_msgs/msg', '/home/turtlebot/ese_team_project/rocon/devel/share/rocon_std_msgs/msg'], 'rocon_service_pair_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_service_pair_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rocon_interaction_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_interaction_msgs/msg'], 'uuid_msgs': ['/opt/ros/indigo/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c44b146c4dbd365e79e0f9e065f21d8";
  }

  static const char* value(const ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c44b146c4dbd365ULL;
  static const uint64_t static_value2 = 0xe79e0f9e065f21d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rocon_interaction_msgs/InteractiveClients";
  }

  static const char* value(const ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# \n\
# Two lists are included here to distinguish between idle clients and those that\n\
# are currently running an app.\n\
#\n\
InteractiveClient[] idle_clients\n\
InteractiveClient[] running_clients\n\
\n\
================================================================================\n\
MSG: rocon_interaction_msgs/InteractiveClient\n\
# \n\
# Describes an interactive concert client.\n\
#\n\
# Unique names - human consumable rocon name as well as globally unique name\n\
# provided by the remocon client.\n\
\n\
string name\n\
uuid_msgs/UniqueID id\n\
\n\
rocon_std_msgs/PlatformInfo platform_info\n\
\n\
# easy to read display names of interactions running on this remocon\n\
string[] running_interactions\n\
\n\
================================================================================\n\
MSG: uuid_msgs/UniqueID\n\
# A universally unique identifier (UUID).\n\
#\n\
#  http://en.wikipedia.org/wiki/Universally_unique_identifier\n\
#  http://tools.ietf.org/html/rfc4122.html\n\
\n\
uint8[16] uuid\n\
\n\
================================================================================\n\
MSG: rocon_std_msgs/PlatformInfo\n\
# Provides platform details for robots, software or human\n\
# interactive devices.\n\
\n\
########################### Variables ###########################\n\
\n\
# rocon universal resource identifier\n\
string uri\n\
# rocon version compatibility identifier (used when connecting to concerts)\n\
string version\n\
Icon icon\n\
\n\
================================================================================\n\
MSG: rocon_std_msgs/Icon\n\
# Used to idenfity the original package/filename resource this icon was/is to be loaded from\n\
# This typically doesn't have to be set, but can be very useful when loading icons from yaml definitions.\n\
string resource_name\n\
\n\
# Image data format.  \"jpeg\" or \"png\"\n\
string format\n\
\n\
# Image data.\n\
uint8[] data\n\
";
  }

  static const char* value(const ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.idle_clients);
      stream.next(m.running_clients);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InteractiveClients_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rocon_interaction_msgs::InteractiveClients_<ContainerAllocator>& v)
  {
    s << indent << "idle_clients[]" << std::endl;
    for (size_t i = 0; i < v.idle_clients.size(); ++i)
    {
      s << indent << "  idle_clients[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rocon_interaction_msgs::InteractiveClient_<ContainerAllocator> >::stream(s, indent + "    ", v.idle_clients[i]);
    }
    s << indent << "running_clients[]" << std::endl;
    for (size_t i = 0; i < v.running_clients.size(); ++i)
    {
      s << indent << "  running_clients[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::rocon_interaction_msgs::InteractiveClient_<ContainerAllocator> >::stream(s, indent + "    ", v.running_clients[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_INTERACTIVECLIENTS_H
