// Generated by gencpp from file rocon_interaction_msgs/RemoconStatus.msg
// DO NOT EDIT!


#ifndef ROCON_INTERACTION_MSGS_MESSAGE_REMOCONSTATUS_H
#define ROCON_INTERACTION_MSGS_MESSAGE_REMOCONSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <rocon_std_msgs/PlatformInfo.h>

namespace rocon_interaction_msgs
{
template <class ContainerAllocator>
struct RemoconStatus_
{
  typedef RemoconStatus_<ContainerAllocator> Type;

  RemoconStatus_()
    : platform_info()
    , uuid()
    , running_interactions()
    , version()  {
    }
  RemoconStatus_(const ContainerAllocator& _alloc)
    : platform_info(_alloc)
    , uuid(_alloc)
    , running_interactions(_alloc)
    , version(_alloc)  {
  (void)_alloc;
    }



   typedef  ::rocon_std_msgs::PlatformInfo_<ContainerAllocator>  _platform_info_type;
  _platform_info_type platform_info;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _uuid_type;
  _uuid_type uuid;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _running_interactions_type;
  _running_interactions_type running_interactions;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _version_type;
  _version_type version;




  typedef boost::shared_ptr< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RemoconStatus_

typedef ::rocon_interaction_msgs::RemoconStatus_<std::allocator<void> > RemoconStatus;

typedef boost::shared_ptr< ::rocon_interaction_msgs::RemoconStatus > RemoconStatusPtr;
typedef boost::shared_ptr< ::rocon_interaction_msgs::RemoconStatus const> RemoconStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rocon_interaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'rocon_std_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_std_msgs/msg', '/home/turtlebot/ese_team_project/rocon/devel/share/rocon_std_msgs/msg'], 'rocon_service_pair_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_service_pair_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rocon_interaction_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_interaction_msgs/msg'], 'uuid_msgs': ['/opt/ros/indigo/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7efa16bc8273de65267b6c5877e7d5e";
  }

  static const char* value(const ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7efa16bc8273de6ULL;
  static const uint64_t static_value2 = 0x5267b6c5877e7d5eULL;
};

template<class ContainerAllocator>
struct DataType< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rocon_interaction_msgs/RemoconStatus";
  }

  static const char* value(const ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Used by the remocons to inform the concert of it's current status. They should\n\
# publish this as a latched publisher.\n\
\n\
rocon_std_msgs/PlatformInfo platform_info\n\
# The remocon id\n\
# This should be a '32 character Type 4 uuid hex string'\n\
string uuid\n\
\n\
\n\
# We should be using this, but java can't handle the type, reintegrate when we bugfix.\n\
# uuid_msgs/UniqueID[] running_interactions\n\
\n\
# This is a crc32 hash code we use because of the above.\n\
int32[] running_interactions\n\
\n\
# rocon version compatibility identifier (used when connecting to concerts)\n\
string version\n\
\n\
================================================================================\n\
MSG: rocon_std_msgs/PlatformInfo\n\
# Provides platform details for robots, software or human\n\
# interactive devices.\n\
\n\
########################### Variables ###########################\n\
\n\
# rocon universal resource identifier\n\
string uri\n\
# rocon version compatibility identifier (used when connecting to concerts)\n\
string version\n\
Icon icon\n\
\n\
================================================================================\n\
MSG: rocon_std_msgs/Icon\n\
# Used to idenfity the original package/filename resource this icon was/is to be loaded from\n\
# This typically doesn't have to be set, but can be very useful when loading icons from yaml definitions.\n\
string resource_name\n\
\n\
# Image data format.  \"jpeg\" or \"png\"\n\
string format\n\
\n\
# Image data.\n\
uint8[] data\n\
";
  }

  static const char* value(const ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.platform_info);
      stream.next(m.uuid);
      stream.next(m.running_interactions);
      stream.next(m.version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoconStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rocon_interaction_msgs::RemoconStatus_<ContainerAllocator>& v)
  {
    s << indent << "platform_info: ";
    s << std::endl;
    Printer< ::rocon_std_msgs::PlatformInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.platform_info);
    s << indent << "uuid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.uuid);
    s << indent << "running_interactions[]" << std::endl;
    for (size_t i = 0; i < v.running_interactions.size(); ++i)
    {
      s << indent << "  running_interactions[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.running_interactions[i]);
    }
    s << indent << "version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROCON_INTERACTION_MSGS_MESSAGE_REMOCONSTATUS_H
