(cl:in-package rocon_app_manager_msgs-msg)
(cl:export '(BLACKLISTED_RAPPS-VAL
          BLACKLISTED_RAPPS
          NON_WHITELISTED_RAPPS-VAL
          NON_WHITELISTED_RAPPS
          PLATFORM_INCOMPATIBLE_RAPPS-VAL
          PLATFORM_INCOMPATIBLE_RAPPS
          CAPABILITIES_INCOMPATIBLE_RAPPS-VAL
          CAPABILITIES_INCOMPATIBLE_RAPPS
))