; Auto-generated. Do not edit!


(cl:in-package rocon_app_manager_msgs-msg)


;//! \htmlinclude IncompatibleRappList.msg.html

(cl:defclass <IncompatibleRappList> (roslisp-msg-protocol:ros-message)
  ((blacklisted_rapps
    :reader blacklisted_rapps
    :initarg :blacklisted_rapps
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (non_whitelisted_rapps
    :reader non_whitelisted_rapps
    :initarg :non_whitelisted_rapps
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (platform_incompatible_rapps
    :reader platform_incompatible_rapps
    :initarg :platform_incompatible_rapps
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element ""))
   (capabilities_incompatible_rapps
    :reader capabilities_incompatible_rapps
    :initarg :capabilities_incompatible_rapps
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass IncompatibleRappList (<IncompatibleRappList>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <IncompatibleRappList>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'IncompatibleRappList)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rocon_app_manager_msgs-msg:<IncompatibleRappList> is deprecated: use rocon_app_manager_msgs-msg:IncompatibleRappList instead.")))

(cl:ensure-generic-function 'blacklisted_rapps-val :lambda-list '(m))
(cl:defmethod blacklisted_rapps-val ((m <IncompatibleRappList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rocon_app_manager_msgs-msg:blacklisted_rapps-val is deprecated.  Use rocon_app_manager_msgs-msg:blacklisted_rapps instead.")
  (blacklisted_rapps m))

(cl:ensure-generic-function 'non_whitelisted_rapps-val :lambda-list '(m))
(cl:defmethod non_whitelisted_rapps-val ((m <IncompatibleRappList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rocon_app_manager_msgs-msg:non_whitelisted_rapps-val is deprecated.  Use rocon_app_manager_msgs-msg:non_whitelisted_rapps instead.")
  (non_whitelisted_rapps m))

(cl:ensure-generic-function 'platform_incompatible_rapps-val :lambda-list '(m))
(cl:defmethod platform_incompatible_rapps-val ((m <IncompatibleRappList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rocon_app_manager_msgs-msg:platform_incompatible_rapps-val is deprecated.  Use rocon_app_manager_msgs-msg:platform_incompatible_rapps instead.")
  (platform_incompatible_rapps m))

(cl:ensure-generic-function 'capabilities_incompatible_rapps-val :lambda-list '(m))
(cl:defmethod capabilities_incompatible_rapps-val ((m <IncompatibleRappList>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rocon_app_manager_msgs-msg:capabilities_incompatible_rapps-val is deprecated.  Use rocon_app_manager_msgs-msg:capabilities_incompatible_rapps instead.")
  (capabilities_incompatible_rapps m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <IncompatibleRappList>) ostream)
  "Serializes a message object of type '<IncompatibleRappList>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'blacklisted_rapps))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'blacklisted_rapps))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'non_whitelisted_rapps))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'non_whitelisted_rapps))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'platform_incompatible_rapps))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'platform_incompatible_rapps))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'capabilities_incompatible_rapps))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'capabilities_incompatible_rapps))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <IncompatibleRappList>) istream)
  "Deserializes a message object of type '<IncompatibleRappList>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'blacklisted_rapps) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'blacklisted_rapps)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'non_whitelisted_rapps) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'non_whitelisted_rapps)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'platform_incompatible_rapps) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'platform_incompatible_rapps)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'capabilities_incompatible_rapps) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'capabilities_incompatible_rapps)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<IncompatibleRappList>)))
  "Returns string type for a message object of type '<IncompatibleRappList>"
  "rocon_app_manager_msgs/IncompatibleRappList")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'IncompatibleRappList)))
  "Returns string type for a message object of type 'IncompatibleRappList"
  "rocon_app_manager_msgs/IncompatibleRappList")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<IncompatibleRappList>)))
  "Returns md5sum for a message object of type '<IncompatibleRappList>"
  "f8b60bc2510b0df387f6623f3db3a079")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'IncompatibleRappList)))
  "Returns md5sum for a message object of type 'IncompatibleRappList"
  "f8b60bc2510b0df387f6623f3db3a079")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<IncompatibleRappList>)))
  "Returns full string definition for message of type '<IncompatibleRappList>"
  (cl:format cl:nil "# List all apps which were filtered for some reason or another~%~%string[] blacklisted_rapps~%string[] non_whitelisted_rapps~%string[] platform_incompatible_rapps~%string[] capabilities_incompatible_rapps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'IncompatibleRappList)))
  "Returns full string definition for message of type 'IncompatibleRappList"
  (cl:format cl:nil "# List all apps which were filtered for some reason or another~%~%string[] blacklisted_rapps~%string[] non_whitelisted_rapps~%string[] platform_incompatible_rapps~%string[] capabilities_incompatible_rapps~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <IncompatibleRappList>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'blacklisted_rapps) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'non_whitelisted_rapps) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'platform_incompatible_rapps) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'capabilities_incompatible_rapps) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <IncompatibleRappList>))
  "Converts a ROS message object to a list"
  (cl:list 'IncompatibleRappList
    (cl:cons ':blacklisted_rapps (blacklisted_rapps msg))
    (cl:cons ':non_whitelisted_rapps (non_whitelisted_rapps msg))
    (cl:cons ':platform_incompatible_rapps (platform_incompatible_rapps msg))
    (cl:cons ':capabilities_incompatible_rapps (capabilities_incompatible_rapps msg))
))
