// Generated by gencpp from file rocon_device_msgs/GetDeviceListRequest.msg
// DO NOT EDIT!


#ifndef ROCON_DEVICE_MSGS_MESSAGE_GETDEVICELISTREQUEST_H
#define ROCON_DEVICE_MSGS_MESSAGE_GETDEVICELISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rocon_device_msgs
{
template <class ContainerAllocator>
struct GetDeviceListRequest_
{
  typedef GetDeviceListRequest_<ContainerAllocator> Type;

  GetDeviceListRequest_()
    {
    }
  GetDeviceListRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetDeviceListRequest_

typedef ::rocon_device_msgs::GetDeviceListRequest_<std::allocator<void> > GetDeviceListRequest;

typedef boost::shared_ptr< ::rocon_device_msgs::GetDeviceListRequest > GetDeviceListRequestPtr;
typedef boost::shared_ptr< ::rocon_device_msgs::GetDeviceListRequest const> GetDeviceListRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rocon_device_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rocon_std_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_std_msgs/msg', '/home/turtlebot/ese_team_project/rocon/devel/share/rocon_std_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'rocon_device_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_device_msgs/msg'], 'rocon_service_pair_msgs': ['/home/turtlebot/ese_team_project/rocon/src/rocon_msgs/rocon_service_pair_msgs/msg'], 'uuid_msgs': ['/opt/ros/indigo/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rocon_device_msgs/GetDeviceListRequest";
  }

  static const char* value(const ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDeviceListRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rocon_device_msgs::GetDeviceListRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROCON_DEVICE_MSGS_MESSAGE_GETDEVICELISTREQUEST_H
