; Auto-generated. Do not edit!


(cl:in-package rocon_service_pair_msgs-msg)


;//! \htmlinclude TestiesPair.msg.html

(cl:defclass <TestiesPair> (roslisp-msg-protocol:ros-message)
  ((pair_request
    :reader pair_request
    :initarg :pair_request
    :type rocon_service_pair_msgs-msg:TestiesPairRequest
    :initform (cl:make-instance 'rocon_service_pair_msgs-msg:TestiesPairRequest))
   (pair_response
    :reader pair_response
    :initarg :pair_response
    :type rocon_service_pair_msgs-msg:TestiesPairResponse
    :initform (cl:make-instance 'rocon_service_pair_msgs-msg:TestiesPairResponse)))
)

(cl:defclass TestiesPair (<TestiesPair>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TestiesPair>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TestiesPair)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rocon_service_pair_msgs-msg:<TestiesPair> is deprecated: use rocon_service_pair_msgs-msg:TestiesPair instead.")))

(cl:ensure-generic-function 'pair_request-val :lambda-list '(m))
(cl:defmethod pair_request-val ((m <TestiesPair>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rocon_service_pair_msgs-msg:pair_request-val is deprecated.  Use rocon_service_pair_msgs-msg:pair_request instead.")
  (pair_request m))

(cl:ensure-generic-function 'pair_response-val :lambda-list '(m))
(cl:defmethod pair_response-val ((m <TestiesPair>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rocon_service_pair_msgs-msg:pair_response-val is deprecated.  Use rocon_service_pair_msgs-msg:pair_response instead.")
  (pair_response m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TestiesPair>) ostream)
  "Serializes a message object of type '<TestiesPair>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pair_request) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pair_response) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TestiesPair>) istream)
  "Deserializes a message object of type '<TestiesPair>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pair_request) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pair_response) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TestiesPair>)))
  "Returns string type for a message object of type '<TestiesPair>"
  "rocon_service_pair_msgs/TestiesPair")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TestiesPair)))
  "Returns string type for a message object of type 'TestiesPair"
  "rocon_service_pair_msgs/TestiesPair")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TestiesPair>)))
  "Returns md5sum for a message object of type '<TestiesPair>"
  "7b5cb9b4ccdb74840ce04ea92d2a141d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TestiesPair)))
  "Returns md5sum for a message object of type 'TestiesPair"
  "7b5cb9b4ccdb74840ce04ea92d2a141d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TestiesPair>)))
  "Returns full string definition for message of type '<TestiesPair>"
  (cl:format cl:nil "~%TestiesPairRequest pair_request~%TestiesPairResponse pair_response~%~%================================================================================~%MSG: rocon_service_pair_msgs/TestiesPairRequest~%uuid_msgs/UniqueID id~%TestiesRequest request~%~%================================================================================~%MSG: uuid_msgs/UniqueID~%# A universally unique identifier (UUID).~%#~%#  http://en.wikipedia.org/wiki/Universally_unique_identifier~%#  http://tools.ietf.org/html/rfc4122.html~%~%uint8[16] uuid~%~%================================================================================~%MSG: rocon_service_pair_msgs/TestiesRequest~%string data~%~%================================================================================~%MSG: rocon_service_pair_msgs/TestiesPairResponse~%uuid_msgs/UniqueID id~%TestiesResponse response~%~%================================================================================~%MSG: rocon_service_pair_msgs/TestiesResponse~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%uuid_msgs/UniqueID id~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TestiesPair)))
  "Returns full string definition for message of type 'TestiesPair"
  (cl:format cl:nil "~%TestiesPairRequest pair_request~%TestiesPairResponse pair_response~%~%================================================================================~%MSG: rocon_service_pair_msgs/TestiesPairRequest~%uuid_msgs/UniqueID id~%TestiesRequest request~%~%================================================================================~%MSG: uuid_msgs/UniqueID~%# A universally unique identifier (UUID).~%#~%#  http://en.wikipedia.org/wiki/Universally_unique_identifier~%#  http://tools.ietf.org/html/rfc4122.html~%~%uint8[16] uuid~%~%================================================================================~%MSG: rocon_service_pair_msgs/TestiesRequest~%string data~%~%================================================================================~%MSG: rocon_service_pair_msgs/TestiesPairResponse~%uuid_msgs/UniqueID id~%TestiesResponse response~%~%================================================================================~%MSG: rocon_service_pair_msgs/TestiesResponse~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%uuid_msgs/UniqueID id~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TestiesPair>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pair_request))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pair_response))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TestiesPair>))
  "Converts a ROS message object to a list"
  (cl:list 'TestiesPair
    (cl:cons ':pair_request (pair_request msg))
    (cl:cons ':pair_response (pair_response msg))
))
