(cl:defpackage turtlebot_msgs-srv
  (:use )
  (:export
   "TAKEPANORAMA"
   "<TAKEPANORAMA-REQUEST>"
   "TAKEPANORAMA-REQUEST"
   "<TAKEPANORAMA-RESPONSE>"
   "TAKEPANORAMA-RESPONSE"
   "SETFOLLOWSTATE"
   "<SETFOLLOWSTATE-REQUEST>"
   "SETFOLLOWSTATE-REQUEST"
   "<SETFOLLOWSTATE-RESPONSE>"
   "SETFOLLOWSTATE-RESPONSE"
  ))

