(cl:defpackage rocon_tutorial_msgs-srv
  (:use )
  (:export
   "GETAVAILABLERESOURCES"
   "<GETAVAILABLERESOURCES-REQUEST>"
   "GETAVAILABLERESOURCES-REQUEST"
   "<GETAVAILABLERESOURCES-RESPONSE>"
   "GETAVAILABLERESOURCES-RESPONSE"
  ))

