# this file list those commands that can be used to test the implemented framework

# rosservice call command to test the systemControlRegisterService with node_name, callback_service and list_dependencies specified
rosservice call /systemControlRegisterService '{node_name : demoNodeClient1, callback_service : demoNodeClient1, list_dependencies : [node1, node2] }'

# roservice call command to test userInterfaceService, this can be used to invoke the framework info service
rosservice call /frameworkInfoService '{queryType: 0}'
rosservice call /frameworkInfoService '{queryType: 1}'

# roservice call command to test userInterfaceService, this can be used to invoke the noderithm switch
rosservice call /userInterfaceService '{reconType: 2, oldNodePackage: reconfigure, oldNode: demoNode1, newNode: demoNode2, newNodePackage: reconfigure}'

# roservice call command to test userInterfaceService, this can be used to invoke the noderithm switch
rosservice call /userInterfaceService '{reconType: 2, oldNodePackage: reconfigure, oldNode: demoNode4, newNode: demoNode8, newNodePackage: reconfigure}'

# roservice call command to test userInterfaceService, this can be used to invoke the noderithm switch
rosservice call /userInterfaceService '{reconType: 2, oldNodePackage: reconfigure, oldNode: demoNode10, newNode: demoNode17, newNodePackage: reconfigure}'

# roservice call command to test userInterfaceService, this can be used to invoke the noderithm switch
rosservice call /userInterfaceService '{reconType: 2, oldNodePackage: reconfigure, oldNode: demoNode18, newNode: demoNode19, newNodePackage: reconfigure}'
