(cl:in-package gateway_msgs-msg)
(cl:export '(GATEWAY_AVAILABLE-VAL
          GATEWAY_AVAILABLE
          TIME_SINCE_LAST_SEEN-VAL
          TIME_SINCE_LAST_SEEN
          PING_LATENCY_MIN-VAL
          PING_LATENCY_MIN
          PING_LATENCY_MAX-VAL
          PING_LATENCY_MAX
          PING_LATENCY_AVG-VAL
          PING_LATENCY_AVG
          PING_LATENCY_MDEV-VAL
          PING_LATENCY_MDEV
          NETWORK_INFO_AVAILABLE-VAL
          NETWORK_INFO_AVAILABLE
          NETWORK_TYPE-VAL
          NETWORK_TYPE
          WIRELESS_BITRATE-VAL
          WIRELESS_BITRATE
          WIRELESS_LINK_QUALITY-VAL
          WIRELESS_LINK_QUALITY
          WIRELESS_SIGNAL_LEVEL-VAL
          WIRELESS_SIGNAL_LEVEL
          WIRELESS_NOISE_LEVEL-VAL
          WIRELESS_NOISE_LEVEL
))