#Type of Reconfiguration - interface/parameter/node
uint8 reconType

#For node reconfiguration

#preserveState - set to "true" when need to load state in the new node
bool preserveState
string oldNode
string oldNodePackage
string newNode
string newNodePackage

#For Parameter reconfiguration
uint8   paramType
string  paramName
bool    boolValue
string  stringValue
int32   intValue
float64  doubleValue

---

uint8 OK = 0
uint8 ERROR = 1
uint8 result
