(cl:in-package concert_msgs-msg)
(cl:export '(RESOURCE_NAME-VAL
          RESOURCE_NAME
          NAME-VAL
          NAME
          DESCRIPTION-VAL
          DESCRIPTION
          AUTHOR-VAL
          AUTHOR
          PRIORITY-VAL
          PRIORITY
          ICON-VAL
          ICON
          LAUNCHER_TYPE-VAL
          LAUNCHER_TYPE
          LAUNCHER-VAL
          LAUNCHER
          INTERACTIONS-VAL
          INTERACTIONS
          PARAMETERS-VAL
          PARAMETERS
          PARAMETERS_DETAIL-VAL
          PARAMETERS_DETAIL
          UUID-VAL
          UUID
          STATUS-VAL
          STATUS
          ENABLED-VAL
          ENABLED
))