(cl:defpackage rocon_std_msgs-srv
  (:use )
  (:export
   "GETPLATFORMINFO"
   "<GETPLATFORMINFO-REQUEST>"
   "GETPLATFORMINFO-REQUEST"
   "<GETPLATFORMINFO-RESPONSE>"
   "GETPLATFORMINFO-RESPONSE"
  ))

