; Auto-generated. Do not edit!


(cl:in-package concert_service_msgs-msg)


;//! \htmlinclude KillTurtlePairRequest.msg.html

(cl:defclass <KillTurtlePairRequest> (roslisp-msg-protocol:ros-message)
  ((id
    :reader id
    :initarg :id
    :type uuid_msgs-msg:UniqueID
    :initform (cl:make-instance 'uuid_msgs-msg:UniqueID))
   (request
    :reader request
    :initarg :request
    :type concert_service_msgs-msg:KillTurtleRequest
    :initform (cl:make-instance 'concert_service_msgs-msg:KillTurtleRequest)))
)

(cl:defclass KillTurtlePairRequest (<KillTurtlePairRequest>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <KillTurtlePairRequest>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'KillTurtlePairRequest)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name concert_service_msgs-msg:<KillTurtlePairRequest> is deprecated: use concert_service_msgs-msg:KillTurtlePairRequest instead.")))

(cl:ensure-generic-function 'id-val :lambda-list '(m))
(cl:defmethod id-val ((m <KillTurtlePairRequest>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader concert_service_msgs-msg:id-val is deprecated.  Use concert_service_msgs-msg:id instead.")
  (id m))

(cl:ensure-generic-function 'request-val :lambda-list '(m))
(cl:defmethod request-val ((m <KillTurtlePairRequest>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader concert_service_msgs-msg:request-val is deprecated.  Use concert_service_msgs-msg:request instead.")
  (request m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <KillTurtlePairRequest>) ostream)
  "Serializes a message object of type '<KillTurtlePairRequest>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'request) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <KillTurtlePairRequest>) istream)
  "Deserializes a message object of type '<KillTurtlePairRequest>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'request) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<KillTurtlePairRequest>)))
  "Returns string type for a message object of type '<KillTurtlePairRequest>"
  "concert_service_msgs/KillTurtlePairRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'KillTurtlePairRequest)))
  "Returns string type for a message object of type 'KillTurtlePairRequest"
  "concert_service_msgs/KillTurtlePairRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<KillTurtlePairRequest>)))
  "Returns md5sum for a message object of type '<KillTurtlePairRequest>"
  "0f974aecea7bf5add789608093b710e2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'KillTurtlePairRequest)))
  "Returns md5sum for a message object of type 'KillTurtlePairRequest"
  "0f974aecea7bf5add789608093b710e2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<KillTurtlePairRequest>)))
  "Returns full string definition for message of type '<KillTurtlePairRequest>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%uuid_msgs/UniqueID id~%KillTurtleRequest request~%~%================================================================================~%MSG: uuid_msgs/UniqueID~%# A universally unique identifier (UUID).~%#~%#  http://en.wikipedia.org/wiki/Universally_unique_identifier~%#  http://tools.ietf.org/html/rfc4122.html~%~%uint8[16] uuid~%~%================================================================================~%MSG: concert_service_msgs/KillTurtleRequest~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%string name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'KillTurtlePairRequest)))
  "Returns full string definition for message of type 'KillTurtlePairRequest"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%uuid_msgs/UniqueID id~%KillTurtleRequest request~%~%================================================================================~%MSG: uuid_msgs/UniqueID~%# A universally unique identifier (UUID).~%#~%#  http://en.wikipedia.org/wiki/Universally_unique_identifier~%#  http://tools.ietf.org/html/rfc4122.html~%~%uint8[16] uuid~%~%================================================================================~%MSG: concert_service_msgs/KillTurtleRequest~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%string name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <KillTurtlePairRequest>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'request))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <KillTurtlePairRequest>))
  "Converts a ROS message object to a list"
  (cl:list 'KillTurtlePairRequest
    (cl:cons ':id (id msg))
    (cl:cons ':request (request msg))
))
