; Auto-generated. Do not edit!


(cl:in-package concert_service_msgs-msg)


;//! \htmlinclude SpawnTurtlePair.msg.html

(cl:defclass <SpawnTurtlePair> (roslisp-msg-protocol:ros-message)
  ((pair_request
    :reader pair_request
    :initarg :pair_request
    :type concert_service_msgs-msg:SpawnTurtlePairRequest
    :initform (cl:make-instance 'concert_service_msgs-msg:SpawnTurtlePairRequest))
   (pair_response
    :reader pair_response
    :initarg :pair_response
    :type concert_service_msgs-msg:SpawnTurtlePairResponse
    :initform (cl:make-instance 'concert_service_msgs-msg:SpawnTurtlePairResponse)))
)

(cl:defclass SpawnTurtlePair (<SpawnTurtlePair>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SpawnTurtlePair>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SpawnTurtlePair)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name concert_service_msgs-msg:<SpawnTurtlePair> is deprecated: use concert_service_msgs-msg:SpawnTurtlePair instead.")))

(cl:ensure-generic-function 'pair_request-val :lambda-list '(m))
(cl:defmethod pair_request-val ((m <SpawnTurtlePair>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader concert_service_msgs-msg:pair_request-val is deprecated.  Use concert_service_msgs-msg:pair_request instead.")
  (pair_request m))

(cl:ensure-generic-function 'pair_response-val :lambda-list '(m))
(cl:defmethod pair_response-val ((m <SpawnTurtlePair>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader concert_service_msgs-msg:pair_response-val is deprecated.  Use concert_service_msgs-msg:pair_response instead.")
  (pair_response m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SpawnTurtlePair>) ostream)
  "Serializes a message object of type '<SpawnTurtlePair>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pair_request) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pair_response) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SpawnTurtlePair>) istream)
  "Deserializes a message object of type '<SpawnTurtlePair>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pair_request) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pair_response) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SpawnTurtlePair>)))
  "Returns string type for a message object of type '<SpawnTurtlePair>"
  "concert_service_msgs/SpawnTurtlePair")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SpawnTurtlePair)))
  "Returns string type for a message object of type 'SpawnTurtlePair"
  "concert_service_msgs/SpawnTurtlePair")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SpawnTurtlePair>)))
  "Returns md5sum for a message object of type '<SpawnTurtlePair>"
  "d40647d6460ee3e522a284534a00ec9f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SpawnTurtlePair)))
  "Returns md5sum for a message object of type 'SpawnTurtlePair"
  "d40647d6460ee3e522a284534a00ec9f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SpawnTurtlePair>)))
  "Returns full string definition for message of type '<SpawnTurtlePair>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%SpawnTurtlePairRequest pair_request~%SpawnTurtlePairResponse pair_response~%~%================================================================================~%MSG: concert_service_msgs/SpawnTurtlePairRequest~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%uuid_msgs/UniqueID id~%SpawnTurtleRequest request~%~%================================================================================~%MSG: uuid_msgs/UniqueID~%# A universally unique identifier (UUID).~%#~%#  http://en.wikipedia.org/wiki/Universally_unique_identifier~%#  http://tools.ietf.org/html/rfc4122.html~%~%uint8[16] uuid~%~%================================================================================~%MSG: concert_service_msgs/SpawnTurtleRequest~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%string name~%~%================================================================================~%MSG: concert_service_msgs/SpawnTurtlePairResponse~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%uuid_msgs/UniqueID id~%SpawnTurtleResponse response~%~%================================================================================~%MSG: concert_service_msgs/SpawnTurtleResponse~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%# The name the spawning actually used (sometimes a modification of your name).~%string name~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SpawnTurtlePair)))
  "Returns full string definition for message of type 'SpawnTurtlePair"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%SpawnTurtlePairRequest pair_request~%SpawnTurtlePairResponse pair_response~%~%================================================================================~%MSG: concert_service_msgs/SpawnTurtlePairRequest~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%uuid_msgs/UniqueID id~%SpawnTurtleRequest request~%~%================================================================================~%MSG: uuid_msgs/UniqueID~%# A universally unique identifier (UUID).~%#~%#  http://en.wikipedia.org/wiki/Universally_unique_identifier~%#  http://tools.ietf.org/html/rfc4122.html~%~%uint8[16] uuid~%~%================================================================================~%MSG: concert_service_msgs/SpawnTurtleRequest~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%string name~%~%================================================================================~%MSG: concert_service_msgs/SpawnTurtlePairResponse~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%uuid_msgs/UniqueID id~%SpawnTurtleResponse response~%~%================================================================================~%MSG: concert_service_msgs/SpawnTurtleResponse~%# ====== DO NOT MODIFY! AUTOGENERATED FROM A SERVICE PAIR DEFINITION ======~%~%# The name the spawning actually used (sometimes a modification of your name).~%string name~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SpawnTurtlePair>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pair_request))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pair_response))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SpawnTurtlePair>))
  "Converts a ROS message object to a list"
  (cl:list 'SpawnTurtlePair
    (cl:cons ':pair_request (pair_request msg))
    (cl:cons ':pair_response (pair_response msg))
))
