(cl:defpackage concert_msgs-srv
  (:use )
  (:export
   "ENABLESERVICE"
   "<ENABLESERVICE-REQUEST>"
   "ENABLESERVICE-REQUEST"
   "<ENABLESERVICE-RESPONSE>"
   "ENABLESERVICE-RESPONSE"
   "UPDATESERVICECONFIG"
   "<UPDATESERVICECONFIG-REQUEST>"
   "UPDATESERVICECONFIG-REQUEST"
   "<UPDATESERVICECONFIG-RESPONSE>"
   "UPDATESERVICECONFIG-RESPONSE"
   "ALLOCATESOFTWARE"
   "<ALLOCATESOFTWARE-REQUEST>"
   "ALLOCATESOFTWARE-REQUEST"
   "<ALLOCATESOFTWARE-RESPONSE>"
   "ALLOCATESOFTWARE-RESPONSE"
  ))

