(cl:defpackage create_node-srv
  (:use )
  (:export
   "SETTURTLEBOTMODE"
   "<SETTURTLEBOTMODE-REQUEST>"
   "SETTURTLEBOTMODE-REQUEST"
   "<SETTURTLEBOTMODE-RESPONSE>"
   "SETTURTLEBOTMODE-RESPONSE"
   "SETDIGITALOUTPUTS"
   "<SETDIGITALOUTPUTS-REQUEST>"
   "SETDIGITALOUTPUTS-REQUEST"
   "<SETDIGITALOUTPUTS-RESPONSE>"
   "SETDIGITALOUTPUTS-RESPONSE"
  ))

